version: '3.8'

services:
  node:
    # Uncomment to pin to a specific version (in this case, the release candidate for 1.1)
    #image: nerdmaster/dmo-node:1.1-rc1

    # You have to expose 6432 to get incoming connections. You probably
    # shouldn't expose 6433 to anything but localhost.
    ports:
      - '6432:6432'
      - '6433:6433'
    environment:
      - RPC_USER=user
      - RPC_PASS=123456
    # Uncomment this if you're on a really low-end server and need journald and
    # docker-compose to use as little RAM as possible. Note that you'll have
    # *no* logs for debugging anything.
    #command: "-printtoconsole=0"

  # Testnet settings so you can have a real node and testnet at the same time
  testnet:
    ports:
      - '16432:16432'
      - '16433:16433'
    environment:
      - RPC_USER=user
      - RPC_PASS=123456
