version: '3.8'

volumes:
  node:

services:
  node:
    image: dynamo-node:v1.0
    container_name: dynamo-node
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - NODE_HOST
      - NODE_RPCPORT
      - NODE_SRVPORT
    volumes:
      - node:/root/.dynamo/
