version: '3.8'

services:
  node:
    # Uncomment to pin to a specific version (in this case, the release candidate for 1.1)
    #image: nerdmaster/dmo-node:1.1-rc1

    # You have to expose 6432 to get incoming connections. You probably
    # shouldn't expose 6433 to anything but localhost.
    ports:
      - '6432:6432'
      - '6433:6433'
    environment:
      - RPC_USER=user
      - RPC_PASS=123456
    # Uncomment this if you're on a really low-end server and need journald and
    # docker-compose to use as little RAM as possible. Note that you'll have
    # *no* logs for debugging anything.
    #command: "-printtoconsole=0"

    # Uncomment the two lines below to inject a hash file
    #volumes:
      #- ./hash_algo.txt:/dynamo/hash_algo.txt

  # Testnet settings so you can have a real node and testnet at the same time
  testnet:
    ports:
      - '16432:16432'
      - '16433:16433'
    environment:
      - RPC_USER=user
      - RPC_PASS=123456

  # Want to tinker with the build image? Here's a way to build it on its own!
  build:
    image: nerdmaster/dmo-node:build
    build:
      dockerfile: Dockerfile
      context: .
      target: build

  # Build image for testnet since it has slight changes to code
  testnet-build:
    image: nerdmaster/dmo-node:testnet-build
    build:
      dockerfile: Dockerfile
      context: .
      target: build
      args:
        - IS_TESTNET=true
