version: '3.8'

volumes:
  node:

services:
  node:
    image: nerdmaster/dmo-node:unstable
    container_name: dynamo-node
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - RPC_USER
      - RPC_PASS
    volumes:
      - node:/dynamo/data:rw
